(dp1
S'output'
p2
S"<type 'exceptions.AttributeError'> 'DAL' object has no attribute 'submissions'"
p3
sS'layer'
p4
S'C:\\Users\\hd\\PycharmProjects\\untitled\\web2py\\applications\\darkcloud1\\controllers/default.py'
p5
sS'code'
p6
S'<code object <module> at 000000000860F0B0, file "C:\\Users\\hd\\PycharmProjects\\untitled\\web2py\\applications\\darkcloud1\\controllers/default.py", line 4>'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "C:\\Users\\hd\\PycharmProjects\\untitled\\web2py\\gluon\\restricted.py", line 219, in restricted\n    exec(ccode, environment)\n  File "C:\\Users\\hd\\PycharmProjects\\untitled\\web2py\\applications\\darkcloud1\\controllers/default.py", line 227, in <module>\n  File "C:\\Users\\hd\\PycharmProjects\\untitled\\web2py\\gluon\\globals.py", line 419, in <lambda>\n    self._caller = lambda f: f()\n  File "C:\\Users\\hd\\PycharmProjects\\untitled\\web2py\\applications\\darkcloud1\\controllers/default.py", line 182, in subscriber\n    devicestemp = db(db.submissions).select(db.submissions.ALL)\n  File "C:\\Users\\hd\\PycharmProjects\\untitled\\web2py\\gluon\\packages\\dal\\pydal\\base.py", line 669, in __getattr__\n    return BasicStorage.__getattribute__(self, key)\nAttributeError: \'DAL\' object has no attribute \'submissions\'\n'
p11
s.